In [ ]:
import tensorflow as tf

In [ ]:
my_tensor = tf.constant([1,3,4])
my_variable = tf.Variable([[2,3],[3,4]])
bool_variable = tf.Variable([False,False,False])
print(bool_variable)
complex_variable = tf.Variable([1+2j,3+4j])
print(complex_variable)
print("as numpy array", my_variable.numpy())
print("again to tensor flow variable", tf.convert_to_tensor(my_variable))

<tf.Variable 'Variable:0' shape=(3,) dtype=bool, numpy=array([False, False, False])>
<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([1.+2.j, 3.+4.j])>
as numpy array [[2 3]
 [3 4]]
again to tensor flow variable tf.Tensor(
[[2 3]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
a = tf.Variable([1,2])
a.assign([4,5])
print(a)
try:
  a.assign([2,3,4])
except Exception as e:print(e) 

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>
Shapes (2,) and (3,) are incompatible


In [ ]:
a = tf.Variable(my_tensor, name='Mart')
print(a.numpy())

[1 3 4]


In [ ]:
step_counter = tf.Variable(1,trainable = False)

In [ ]:
with tf.device('CPU:0'):
  a = tf.Variable([[1,3],[4,3]])
  b = tf.Variable([[2,4],[2,4]])
with tf.device('GPU:0'):
  c = tf.matmul(a,b)
print(c)

tf.Tensor(
[[ 8 16]
 [14 28]], shape=(2, 2), dtype=int32)


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
a = [1,3]
b = [3,4]
c = tf.add(a,b)
print(c)

tf.Tensor([4 7], shape=(2,), dtype=int32)


In [ ]:
# Runing the simple regression model
x = tf.constant(range(10), dtype=tf.float32)
y = 2 * x + 10
print('x:{}', format(x))
print('y:{}', format(y))


x:{} [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
y:{} [10. 12. 14. 16. 18. 20. 22. 24. 26. 28.]


In [ ]:
# creating tes dataset
x_test = tf.constant(range(10,20), dtype= tf.float32)
y_test = 2 * x + 10

In [ ]:
y_mean = y.numpy().mean()
def predict_mean(x):
  y_hat = [y_mean] * len(x)
  return y_hat
y_hat = predict_mean(x)

In [ ]:
errors = (y_hat - y)**2
loss = tf.reduce_mean(errors)
loss.numpy()

33.0

In [ ]:
def loss_mse(x,y,w0,w1):
  y_hat = w0 * x + w1
  error = (y_hat - y)**2
  return tf.reduce_mean(error)

In [ ]:
def compute_gradient(x,y,w0,w1):
  with tf.GradientTape() as tape:
    loss = loss_mse(x,y,w0,w1)
    return tape.gradient(loss,[w0,w1])

In [ ]:
w0 = tf.Variable([0.0])
w1 = tf.Variable([0.0])
dw0, dw1 = compute_gradient(x,y,w0,w1)

In [ ]:
steps = 1000
alpha = 0.02
MSG = "step:{steps} - loss:{loss}, w0:{w0}, w1:{w1} \n"
w0 = tf.Variable(0.0)
w1 = tf.Variable(0.0)
for step in range(1, steps+1):
  dw0, dw1 = compute_gradient(x, y, w0, w1)
  w0.assign_sub(dw0 * alpha)
  w1.assign_sub(dw1 * alpha)
  if step % 100 == 0:
    loss = loss_mse(x,y,w0,w1)
    print(MSG.format(steps=step,loss = loss, w0 = w0.numpy(), w1 = w1.numpy()))


step:100 - loss:2.6615359783172607, w0:2.483504056930542, w1:6.968146324157715 

step:200 - loss:0.27448415756225586, w0:2.1552717685699463, w1:9.026354789733887 

step:300 - loss:0.02830762229859829, w0:2.049863815307617, w1:9.687324523925781 

step:400 - loss:0.002919511403888464, w0:2.0160133838653564, w1:9.899585723876953 

step:500 - loss:0.00030110636726021767, w0:2.0051426887512207, w1:9.967751502990723 

step:600 - loss:3.105618088738993e-05, w0:2.0016515254974365, w1:9.989643096923828 

step:700 - loss:3.2044197268987773e-06, w0:2.000530481338501, w1:9.996673583984375 

step:800 - loss:3.3013247957569547e-07, w0:2.0001704692840576, w1:9.998931884765625 

step:900 - loss:3.4496132172989746e-08, w0:2.0000550746917725, w1:9.999654769897461 

step:1000 - loss:3.654804459074512e-09, w0:2.0000178813934326, w1:9.999887466430664 



In [ ]:
loss = loss_mse(x_test,y_test,w0,w1)
loss.numpy()

400.0059