In [ ]:
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.3.0


In [ ]:
x = tf.constant([[1,4,2],[4,1,5]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 4, 2],
       [4, 1, 5]], dtype=int32)>

In [ ]:
y = x[:,1]
y

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 1], dtype=int32)>

In [ ]:
y = tf.reshape(x,[6,1])
y

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [4],
       [2],
       [4],
       [1],
       [5]], dtype=int32)>

In [ ]:
# rank zero tensors
rank_zero_tensor = tf.constant(4)
print(rank_zero_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
rank_1_tensor = tf.constant([2,4,6])
print(rank_1_tensor)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [ ]:
rank_2_tensor = tf.constant([[1,2],[3,5],[2,1]])
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 5]
 [2 1]], shape=(3, 2), dtype=int32)


In [ ]:
rank_3_tensor = tf.constant([ 
                            [[1,2,4],
                             [2,4,2]],
                            [[3,5,6],
                             [5,5,6]],
                            [[3,5,7],
                             [4,5,7]]
                             ])
print(rank_3_tensor)

tf.Tensor(
[[[1 2 4]
  [2 4 2]]

 [[3 5 6]
  [5 5 6]]

 [[3 5 7]
  [4 5 7]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
np.array(rank_2_tensor)

array([[1, 2],
       [3, 5],
       [2, 1]], dtype=int32)

In [ ]:
rank_2_tensor.numpy()

array([[1, 2],
       [3, 5],
       [2, 1]], dtype=int32)

In [ ]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[3,5],[5,4]])
print('sum = ', tf.add(a,b), '\n')
print('element wise multiplication', tf.multiply(a,b), '\n')
print('matric multiplication', tf.matmul(a,b), '\n')

sum =  tf.Tensor(
[[4 7]
 [8 8]], shape=(2, 2), dtype=int32) 

element wise multiplication tf.Tensor(
[[ 3 10]
 [15 16]], shape=(2, 2), dtype=int32) 

matric multiplication tf.Tensor(
[[13 13]
 [29 31]], shape=(2, 2), dtype=int32) 



In [ ]:
c = tf.constant([[1.0,3.0],[2.0,13.0]])
print('maximum value = ', tf.reduce_max(c), '\n')
print('index of largest value = ', tf.math.argmax(c),'\n')
tf.nn.softmax(c)

maximum value =  tf.Tensor(13.0, shape=(), dtype=float32) 

index of largest value =  tf.Tensor([1 1], shape=(2,), dtype=int64) 



<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.1920291e-01, 8.8079703e-01],
       [1.6701422e-05, 9.9998331e-01]], dtype=float32)>

In [ ]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
x = tf.constant([1,2,1,0,5,7])
print(x.numpy())

[1 2 1 0 5 7]


In [ ]:
print('first element = ', x[0].numpy())
print('last element = ', x[-1].numpy())

first element =  1
last element =  7


In [ ]:
print('rank_2_tensor = ', rank_2_tensor)

rank_2_tensor =  tf.Tensor(
[[1 2]
 [3 5]
 [2 1]], shape=(3, 2), dtype=int32)


In [ ]:
print(rank_2_tensor[1,1].numpy())

5


In [ ]:
print('second row', rank_2_tensor[1,:].numpy())
print('second colom', rank_2_tensor[:,1].numpy())
print('last rom', rank_2_tensor[2,:].numpy())

second row [3 5]
second colom [2 5 1]
last rom [2 1]
